version: "3.8"
services:
  tailscale:
    image: ghcr.io/tailscale/tailscale:latest
    container_name: tailscale
    restart: unless-stopped
    environment:
      - TS_AUTHKEY=${tailscale_authkey}
      - TS_HOSTNAME=${tailscale_hostname}
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ./tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW