---
version: "3"

services:
#   prowlarr:
#     image: lscr.io/linuxserver/prowlarr
#     container_name: prowlarr
#     restart: unless-stopped
#     environment:
#       - PUID=${uid}
#       - PGID=${gid}
#       - TZ=Europe/Berlin
#     volumes:
#       - ./prowlarr/config:/config
#     networks:
#       - arr-stack
#     ports:
#       - 12001:9696

#   radarr:
#     image: lscr.io/linuxserver/radarr
#     container_name: radarr
#     restart: unless-stopped  
#     environment:
#       - PUID=${uid}
#       - PGID=${gid}
#       - TZ=Europe/Berlin  
#     volumes:
#       - ./radarr/config:/config
#       - ./media/movies:/movies
#       - ./downloads:/downloads
#     networks:
#       - arr-stack
#     ports:
#       - 12002:7878

#   sonarr:
#     image: lscr.io/linuxserver/sonarr
#     container_name: sonarr
#     restart: unless-stopped
#     environment:
#       - PUID=${uid}
#       - PGID=${gid}
#       - TZ=Europe/Berlin
#     volumes:
#       - ./sonarr/config:/config
#       - ./media/series:/series
#       - ./downloads:/downloads
#     networks:
#       - arr-stack
#     ports:
#       - 12003:8989

#   sabnzbd:
#     image: lscr.io/linuxserver/sabnzbd
#     container_name: sabnzbd
#     restart: unless-stopped   
#     environment:
#       - PUID=${uid}
#       - PGID=${gid}
#       - TZ=Europe/Berlin
#     volumes:
#       - ./sabnzbd/config:/config
#       - ./downloads:/downloads
#       - ./incomplete-downloads:/incomplete-downloads  
#     networks:
#       - arr-stack
#     ports:
#       - 12004:8080

#   jellyseerr:
#     image: fallenbagel/jellyseerr
#     container_name: jellyseerr
#     restart: unless-stopped
#     environment:
#       - LOG_LEVEL=debug
#       - TZ=Europe/Berlin
#     volumes:
#       - ./jellyseerr/config:/app/config  
#     networks:
#       - arr-stack
#     ports:
#       - 12005:5055
    
#   jellyfin:
#     image: lscr.io/linuxserver/jellyfin
#     container_name: jellyfin
#     restart: unless-stopped
#     environment:
#       - PUID=${uid}
#       - PGID=${gid}
#       - TZ=Europe/Berlin
#     volumes:
#       - ./jellyfin/config:/config
#       - ./media/movies:/movies
#       - ./media/series:/series
#     networks:
#       - arr-stack
#     ports:
#       - 12006:8096
  
#   homepage:
#     image: ghcr.io/gethomepage/homepage
#     container_name: homepage
#     restart: unless-stopped
#     volumes:
#       - ./homepage/config:/app/config
#       - /var/run/docker.sock:/var/run/docker.sock
#     networks:
#       - service
#     ports:
#       - 12000:3000

#   tailscale:
#     image: ghcr.io/tailscale/tailscale
#     container_name: tailscale
#     restart: unless-stopped
#     environment:
#       - TS_AUTHKEY=${tailscale_authkey}
#       - TS_HOSTNAME=${tailscale_hostname}
#       - TS_STATE_DIR=/config
#     volumes:
#       - ./tailscale/config:/config
#       - /dev/net/tun:/dev/net/tun
#     network_mode: host
#     cap_add:
#       - NET_ADMIN
#       - NET_RAW
  hello_world:
    image: hello-world
  
networks:
  service: {}
#   arr-stack: {}
