services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr
    restart: unless-stopped
    environment:
      - PUID=${uid}
      - PGID=${gid}
      - UMASK=${umask}
      - TZ=Europe/Berlin
    volumes:
      - ./radarr:/config
      - /mnt/disk1/media/movies:/movies
      - /mnt/disk1/media/downloads:/downloads
    networks:
      - media
      - caddy_internal

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr
    restart: unless-stopped
    environment:
      - PUID=${uid}
      - PGID=${gid}
      - UMASK=${umask}
      - TZ=Europe/Berlin
    volumes:
      - ./sonarr:/config
      - /mnt/disk1/media/tv:/tv
      - /mnt/disk1/media/downloads:/downloads
    networks:
      - media
      - caddy_internal

  sabnzbd:
    container_name: sabnzbd
    image: lscr.io/linuxserver/sabnzbd
    restart: unless-stopped
    environment:
      - PUID=${uid}
      - PGID=${gid}
      - UMASK=${umask}
      - TZ=Europe/Berlin
    volumes:
      - ./sabnzbd:/config
      - /mnt/disk1/media/downloads:/downloads
      - /mnt/disk1/media/incomplete-downloads:/incomplete-downloads
    networks:
      - media
      - caddy_internal

  overseerr:
    container_name: overseerr
    image: lscr.io/linuxserver/overseerr
    restart: unless-stopped
    environment:
      - PUID=${uid}
      - PGID=${gid}
      - UMASK=${umask}
      - LOG_LEVEL=debug
      - TZ=Europe/Berlin
    volumes:
      - ./overseerr:/config
    networks:
      - media
      - caddy_external

  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex
    restart: unless-stopped
    environment:
      - PUID=${uid}
      - PGID=${gid}
      - UMASK=${umask}
      - TZ=Europe/Berlin
      - PLEX_CLAIM=${plex_claim}
    volumes:
      - ./plex:/config
      - /mnt/disk1/media/movies:/movies
      - /mnt/disk1/media/tv:/tv
      - /mnt/disk1/media/youtube:/youtube
    network_mode: host
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128

  tubearchivist:
    container_name: tubearchivist
    image: bbilly1/tubearchivist
    restart: unless-stopped
    environment:
      - ES_URL=http://tubearchivist_elasticsearch:9200
      - REDIS_HOST=tubearchivist_redis
      - HOST_UID=${uid}
      - HOST_GID=${gid}
      - TA_HOST=192.168.178.59 tubearchivist.${duckdns_domain}.duckdns.org
      - TA_USERNAME=${tubearchivist_username}
      - TA_PASSWORD=${tubearchivist_password}
      - ELASTIC_PASSWORD=${tubearchivist_elasticsearch_password}
      - TZ=Europe/Berlin
    volumes:
      - /mnt/disk1/media/youtube:/youtube
      - ./tubearchivist:/cache
    networks:
      - tubearchivist
      - caddy_internal
    ports:
      - 8000:8000
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8000/health
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s

  tubearchivist_redis:
    container_name: tubearchivist_redis
    image: redis/redis-stack-server
    restart: unless-stopped
    volumes:
      - ./tubearchivist_redis:/data
    networks:
      - tubearchivist

  tubearchivist_elasticsearch:
    container_name: tubearchivist_elasticsearch
    image: bbilly1/tubearchivist-es
    restart: unless-stopped
    environment:
      - ELASTIC_PASSWORD=${tubearchivist_elasticsearch_password}
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=true
      - discovery.type=single-node
      - path.repo=/usr/share/elasticsearch/data/snapshot
    volumes:
      - ./tubearchivist_elasticsearch:/usr/share/elasticsearch/data
    networks:
      - tubearchivist
    ulimits:
      memlock:
        soft: -1
        hard: -1
        
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /mnt/disk1/media/audiobooks:/audiobooks
      - /mnt/disk1/media/podcasts:/podcasts
      - ./audiobookshelf/config:/config
      - ./audiobookshelf/metadata:/metadata
    networks:
      - media
      - caddy_internal

networks:
  media:
    name: media
    driver: bridge
  tubearchivist:
    name: tubearchivist
    driver: bridge
  caddy_internal:
    external: true
  caddy_external:
    external: true