- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: apt-get update
      ansible.builtin.apt:
        update_cache: yes

    - name: apt-get upgrade
      ansible.builtin.apt:
        name: "*"
        state: latest
    
    - name: install necessary packages
      ansible.builtin.apt:
        name:
          - ca-certificates 
          - curl
        state: latest
    
    - name: add GPG key
      ansible.builtin.shell:
        cmd: |
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc          
          sudo chmod a+r /etc/apt/keyrings/docker.asc

    - name: add docker repo
      ansible.builtin.shell:
        cmd: |
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: apt-get update
      ansible.builtin.apt:
        update_cache: yes
    
    - name: install docker
      ansible.builtin.apt:
        name:
          - docker-ce 
          - docker-ce-cli 
          - containerd.io 
          - docker-buildx-plugin 
          - docker-compose-plugin
        state: latest

    - name: add docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: add user to docker group
      ansible.builtin.user:
        name: pi
        groups: docker
        append: yes